// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMnwX-QmV1RB0mgvKqF4wlBveYZ-R9LeY',
    appId: '1:257333404922:android:a5332779805b8be5ca5543',
    messagingSenderId: '257333404922',
    projectId: 'cnc-db-crud',
    databaseURL: 'https://cnc-db-crud-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cnc-db-crud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNnysii4_P_OaWwgqevkRI-QgLfS7oSGk',
    appId: '1:257333404922:ios:f607c32daa0a7370ca5543',
    messagingSenderId: '257333404922',
    projectId: 'cnc-db-crud',
    databaseURL: 'https://cnc-db-crud-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cnc-db-crud.appspot.com',
    iosBundleId: 'com.example.cncCrud',
  );
}
